apiVersion: apps/v1
kind: Deployment
metadata:
  name: logout
  namespace: megabank-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: logout
  template:
    metadata:
      labels:
        deployment: logout
    spec:
      containers:
      - name: logout
        image: quay.io/mmondics/mbsvc-pg:v1-manifest
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          value: passw0rd
        - name: JDBCNAME
          value: jdbc/MegaBankDataSource
        - name: POSTGRES_SSL_MODE
          value: disable
        - name: MBPG_SERVICE_HOST
          value: mbpg.megabank-pg.svc.cluster.local
        - name: MBPG_SERVICE_PORT
          value: '5432'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logout
    app.kubernetes.io/component: logout
    app.kubernetes.io/instance: logout
    app.kubernetes.io/name: mbsvc
  name: logout
  namespace: megabank-pg
spec:
  ports:
  - name: 9080-tcp
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: 9443-tcp
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    deployment: logout
