apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer
  namespace: megabank-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: transfer
  template:
    metadata:
      labels:
        deployment: transfer
    spec:
      containers:
      - name: transfer
        image: quay.io/mmondics/mbsvc-pg:v4-manifest
        imagePullPolicy: Always
        env:
        - name: POSTGRES_DATABASE_NAME
          value: app
        - name: POSTGRES_USERNAME
          value: app
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-microservice-app
              key: password
        - name: JDBCNAME
          value: jdbc/MegaBankDataSource
        - name: POSTGRES_SSL_MODE
          value: disable
        - name: MBPG_SERVICE_HOST
          value: cluster-microservice-rw.megabank-pg.svc.cluster.local
        - name: MBPG_SERVICE_PORT
          value: '5432'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: transfer
    app.kubernetes.io/component: transfer
    app.kubernetes.io/instance: transfer
    app.kubernetes.io/name: mbsvc
  name: transfer
  namespace: megabank-pg
spec:
  ports:
  - name: 9080-tcp
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: 9443-tcp
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    deployment: transfer
